       IDENTIFICATION DIVISION.
       PROGRAM-ID. GRADETRACKER.
       AUTHOR. AHYAAN-MALIK.

       ENVIRONMENT DIVISION. 

       DATA DIVISION. 
       WORKING-STORAGE SECTION. 
       01 WS-STUDENT-NAME PIC X(30).
       01 WS-SCORE1 PIC 999V99.
       01 WS-SCORE2 PIC 999V99.
       01 WS-SCORE3 PIC 999V99.
       01 WS-TOTAL-SCORE PIC 999V99.
       01 WS-AVERAGE-SCORE PIC ZZ9V99.
       01 WS-AVERAGE-SCORE-DISPLAY PIC ZZ9.99.

       PROCEDURE DIVISION.
       MAIN-PARA.
           DISPLAY 'Grade Tracker'
           DISPLAY '------------'
           DISPLAY 'Enter Student Name: '
           ACCEPT WS-STUDENT-NAME
           DISPLAY 'Enter Score 1 (0-100): '
           ACCEPT WS-SCORE1
           DISPLAY 'Enter Score 2 (0-100): '
           ACCEPT WS-SCORE2
           DISPLAY 'Enter Score 3 (0-100): '
           ACCEPT WS-SCORE3
           ADD WS-SCORE1 TO WS-SCORE2 GIVING WS-TOTAL-SCORE
           ADD WS-SCORE3 TO WS-TOTAL-SCORE GIVING WS-TOTAL-SCORE
           DIVIDE WS-TOTAL-SCORE BY 3 GIVING WS-AVERAGE-SCORE
           MOVE WS-AVERAGE-SCORE TO WS-AVERAGE-SCORE-DISPLAY
           DISPLAY 'Student: ' WS-STUDENT-NAME
           DISPLAY 'Average Score: '  WS-AVERAGE-SCORE-DISPLAY
           STOP RUN.
